### PR TITLE
RTFCompressed support

### PR DESCRIPTION
**Pull request by seeker25**
Added in support for BodyRtf, RTFCompressed.
Included helpers RTFCompressor.cs, Crc32Calculator.cs. Also the spec and documentation with MS-OXRTFCP.

### CODE REVIEW

**Comment by Sicos1977** [comment]
Thanks, I will merge your code this evening (morning here now in the Netherlands)

**Comment by seeker25** [comment]
Awesome, tried to make the classes fit the best I could. Hoping to get the
contact groups going tomorrow or the next day.

**Comment by Sicos1977** [comment]
It could be possible that groups use something simular like this --> https://github.com/Sicos1977/MsgKit/blob/master/MsgKit/Structures/UnsendableRecipients.cs

**Comment by seeker25** [comment]
I ran the appointment test. Seems to be stuck trying to declare the
variable appointment. Location twice.

I looked inside of Appointment.cs

It looks like there has been a repeat of code.


            var namedProperties = new NamedProperties(propertiesStream);
//Uses the top level properties.
            namedProperties.AddProperty(NamedPropertyTags.PidLidLocation,
Location);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentStartWhole,
MeetingStart);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentEndWhole,
MeetingEnd);

namedProperties.AddProperty(NamedPropertyTags.PidLidMeetingType,
MeetingType.mtgRequest);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentSubType,
AllDay);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentStateFlags,
AppointmentState.asfMeeting);

            if (BodyRtfCompressed)
            {

propertiesStream.AddProperty(PropertyTags.PR_RTF_COMPRESSED,
RTFCompressor.Compress(Encoding.ASCII.GetBytes(BodyRtf)));
                propertiesStream.AddProperty(PropertyTags.PR_RTF_IN_SYNC,
true);
            }

            var nps = new NamedProperties(propertiesStream); //Uses the top
level properties.
            nps.AddProperty(NamedPropertyTags.PidLidLocation, Location);
            nps.AddProperty(NamedPropertyTags.PidLidAppointmentStartWhole,
MeetingStart);
            nps.AddProperty(NamedPropertyTags.PidLidAppointmentEndWhole,
MeetingEnd);
            nps.AddProperty(NamedPropertyTags.PidLidMeetingType,
0x00000001);
            nps.AddProperty(NamedPropertyTags.PidLidAppointmentSubType,
AllDay);
            nps.AddProperty(NamedPropertyTags.PidLidAppointmentStateFlags,
1);

**Comment by seeker25** [comment]
Sorry stuck trying to define a named variable - Location. twice.. It's
early haha.

**Comment by seeker25** [comment]
Should be :



            if (BodyRtfCompressed)
            {

propertiesStream.AddProperty(PropertyTags.PR_RTF_COMPRESSED,
RTFCompressor.Compress(Encoding.ASCII.GetBytes(BodyRtf)));
                propertiesStream.AddProperty(PropertyTags.PR_RTF_IN_SYNC,
true);
            }

            var namedProperties = new NamedProperties(propertiesStream);
//Uses the top level properties.
            namedProperties.AddProperty(NamedPropertyTags.PidLidLocation,
Location);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentStartWhole,
MeetingStart);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentEndWhole,
MeetingEnd);

namedProperties.AddProperty(NamedPropertyTags.PidLidMeetingType,
MeetingType.mtgRequest);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentSubType,
AllDay);

namedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentStateFlags,
AppointmentState.asfMeeting);

            namedProperties.WriteProperties(rootStorage);



I think

**Comment by seeker25** [comment]
I think it's the same mechanism UnsendableRecipents uses..
(RecipientRowDisplayType.DistributionList)
But it doesn't seem like PidLidAppointmentUnsendableRecipients is actually
set in the .msg file.

**Comment by seeker25** [comment]
Easy just had to extend the recipients, add in the two properties

            propertiesStream.AddProperty(PropertyTags.PR_OBJECT_TYPE,
ObjectType);
            propertiesStream.AddProperty(PropertyTags.PR_DISPLAY_TYPE,
DisplayType);

**Pull request merged**
